const BASE_URL = ""
export default {

    REGISTER_STUDENT: `${BASE_URL}/auth/registerStudent`,
    REGISTER_TEACHER: `${BASE_URL}/auth/registerTeacher`,
    LOGIN: `${BASE_URL}/auth/login`,
    REFRESH_TOKEN: `${BASE_URL}/auth/refresh`,

    STUDENTS: `${BASE_URL}/students`,

    CREATE_MULTIPLE_CHOICE_EXERCISE: `${BASE_URL}/multipleChoiceExercise/post`,
    GET_MULTIPLE_CHOICE_BY_CREATED_BY: `${BASE_URL}/multipleChoiceExercise/getByCreatedBy`,
    GET_MULTIPLE_CHOICE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/multipleChoiceExercise/getByCreatedByAndPurpose`,
    GET_PRACTICE_MULTIPLE_CHOICE_EXERCISE_BY_CREATED_BY_AND_STUDENT_ID_GROUP_BY_SOLVED: `${BASE_URL}/multipleChoiceExercise/getPracticeByCreatedByAndStudentIdGroupBySolved`,


    CREATE_LINEAR_SIGN_TABLE_EXERCISE: `${BASE_URL}/signTableExercise/postLinear`,
    CREATE_QUADRATIC_SIGN_TABLE_EXERCISE: `${BASE_URL}/signTableExercise/postQuadratic`,
    GET_LINEAR_SIGN_TABLE_BY_CREATED_BY: `${BASE_URL}/signTableExercise/getByTypeLinearAndCreatedBy`,
    GET_LINEAR_SIGN_TABLE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/signTableExercise/getByTypeLinearAndCreatedByAndPurpose`,
    GET_PRACTICE_LINEAR_SIGN_TABLE_EXERCISE_BY_CREATED_BY_GROUP_BY_SOLVED: `${BASE_URL}/signTableExercise/getLinearSignTablePracticeByCreatedByAndStudentIdGroupBySolved`,
    GET_QUADRATIC_SIGN_TABLE_BY_CREATED_BY: `${BASE_URL}/signTableExercise/getByTypeQuadraticAndCreatedBy`,
    GET_QUADRATIC_SIGN_TABLE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/signTableExercise/getByTypeQuadraticAndCreatedByAndPurpose`,
    GET_PRACTICE_QUADRATIC_SIGN_TABLE_EXERCISE_BY_CREATED_BY_GROUP_BY_SOLVED: `${BASE_URL}/signTableExercise/getQuadraticSignTablePracticeByCreatedByAndStudentIdGroupBySolved`,

    CREATE_PROBABILITIES_EXERCISE: `${BASE_URL}/probabilitiesExercise/post`,
    GET_PROBABILITIES_EXERCISE_BY_ID: `${BASE_URL}/probabilitiesExercise/getById`,
    GET_PROBABILITIES_EXERCISE_BY_CREATED_BY: `${BASE_URL}/probabilitiesExercise/getByCreatedBy`,
    GET_PROBABILITIES_EXERCISE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/probabilitiesExercise/getByCreatedByAndPurpose`,
    GET_PRACTICE_PROBABILITIES_EXERCISE_BY_CREATED_BY_AND_STUDENT_ID_GROUP_BY_SOLVED: `${BASE_URL}/probabilitiesExercise/getPracticeByCreatedByAndStudentIdGroupBySolved`,
    DELETE_PROBABILITIES_EXERCISE_BY_ID: `${BASE_URL}/probabilitiesExercise/deleteById`,
    DELETE_PROBABILITIES_EXERCISE_BY_CREATED_BY: `${BASE_URL}/probabilitiesExercise/deleteByCreatedBy`,

    CREATE_STATISTICS_EXERCISE: `${BASE_URL}/statisticsExercise/post`,
    GET_STATISTICS_EXERCISE_BY_ID: `${BASE_URL}/statisticsExercise/getById`,
    GET_STATISTICS_EXERCISE_BY_CREATED_BY: `${BASE_URL}/statisticsExercise/getByCreatedBy`,
    GET_STATISTICS_EXERCISE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/statisticsExercise/getByCreatedByAndPurpose`,
    GET_STATISTICS_EXERCISE_BY_CREATED_BY_AND_EXERCISE_TYPE: `${BASE_URL}/statisticsExercise/getByCreatedByAndExerciseType`,
    GET_PRACTICE_STATISTICS_EXERCISE_BY_CREATED_BY_AND_STUDENT_ID_GROUP_BY_SOLVED: `${BASE_URL}/statisticsExercise/getPracticeByCreatedByAndStudentIdGroupBySolved`,
    DELETE_STATISTICS_EXERCISE_BY_ID: `${BASE_URL}/statisticsExercise/deleteById`,
    DELETE_STATISTICS_EXERCISE_BY_CREATED_BY: `${BASE_URL}/statisticsExercise/deleteByCreatedBy`,

    CREATE_FINANCIAL_EXERCISE: `${BASE_URL}/financialExercise/post`,
    GET_FINANCIAL_EXERCISE_BY_ID: `${BASE_URL}/financialExercise/getById`,
    GET_FINANCIAL_EXERCISE_BY_CREATED_BY: `${BASE_URL}/financialExercise/getByCreatedBy`,
    GET_FINANCIAL_EXERCISE_BY_CREATED_BY_AND_PURPOSE: `${BASE_URL}/financialExercise/getByCreatedByAndPurpose`,
    GET_FINANCIAL_EXERCISE_BY_CREATED_BY_AND_EXERCISE_TYPE: `${BASE_URL}/financialExercise/getByCreatedByAndExerciseType`,
    GET_PRACTICE_FINANCIAL_EXERCISE_BY_CREATED_BY_GROUP_BY_SOLVED: `${BASE_URL}/financialExercise/getPracticeByCreatedByAndStudentIdGroupBySolved`,
    DELETE_FINANCIAL_EXERCISE_BY_ID: `${BASE_URL}/financialExercise/deleteById`,
    DELETE_FINANCIAL_EXERCISE_BY_CREATED_BY: `${BASE_URL}/financialExercise/deleteByCreatedBy`,

    CREATE_QUIZ: `${BASE_URL}/quiz/post`,
    GET_QUIZ_BY_CREATED_BY: `${BASE_URL}/quiz/getByCreatedBy`,
    GET_QUIZ_BY_ID: `${BASE_URL}/quiz/getById`,
    GET_QUIZ_BY_CREATED_BY_AND_QUIZ_TYPE: `${BASE_URL}/quiz/getByCreatedByAndQuizType`,
    GET_QUIZ_BY_CREATED_BY_AND_QUIZ_TYPE_AND_VISIBILITY: `${BASE_URL}/quiz/getByCreatedByAndQuizTypeAndVisibility`,
    UPDATE_QUIZ_VISIBILITY: `${BASE_URL}/quiz/updateVisibility`,
    DELETE_QUIZ_BY_ID: `${BASE_URL}/quiz/deleteById`,
    DELETE_QUIZ_BY_CREATED_BY: `${BASE_URL}/quiz/deleteByCreated_By`,

    GET_STUDENT_QUIZ_BY_ID: `${BASE_URL}/studentQuiz/getById`,
    GET_STUDENT_QUIZ_BY_QUIZ_ID: `${BASE_URL}/studentQuiz/getByQuizId`,
    GET_STUDENT_QUIZ_BY_STUDENT_ID: `${BASE_URL}/studentQuiz/getByStudentId`,
    GET_STUDENT_QUIZ_BY_STUDENT_ID_AND_QUIZ_ID: `${BASE_URL}/studentQuiz/getByStudentIdAndQuizId`,
    UPDATE_STUDENT_QUIZ: `${BASE_URL}/studentQuiz/update`,
    UPDATE_STUDENT_QUIZ_TRIES_LEFT: `${BASE_URL}/studentQuiz/updateTriesLeft`,
    DECREASE_STUDENT_QUIZ_TRIES_LEFT: `${BASE_URL}/studentQuiz/decreaseTriesLeft`,
    GET_STUDENT_QUIZ_BY_QUIZ_ID_AND_SOLVED: `${BASE_URL}/studentQuiz/getByQuizIdAndSolved`,
    GET_STUDENT_QUIZ_BY_QUIZ_ID_AND_NOT_SOLVED: `${BASE_URL}/studentQuiz/getByQuizIdAndNotSolved`,
    GET_STUDENT_QUIZ_BY_STUDENT_ID_AND_SOLVED: `${BASE_URL}/studentQuiz/getByStudentIdAndSolved`,
    GET_STUDENT_QUIZ_PERFORMANCE_BY_STUDENT_ID: `${BASE_URL}/studentQuizPerformance/getByStudentId`,

    GET_STUDENT_STATS_BY_ID: `${BASE_URL}/studentStats/getById`,
    GET_STUDENT_STATS_BY_STUDENT_ID: `${BASE_URL}/studentStats/getByStudentId`,
    GET_STUDENT_STATS_BY_TEACHER_ID: `${BASE_URL}/studentStats/getByTeacherId`,
    UPDATE_STUDENT_STATS: `${BASE_URL}/studentStats/update`,
    INCREASE_EXERCISE_SOLUTION_GRANT: `${BASE_URL}/studentStats/increaseExerciseSolutionGrant`,
    DECREASE_EXERCISE_SOLUTION_GRANT: `${BASE_URL}/studentStats/decreaseExerciseSolutionGrant`,
    INCREASE_QUIZ_TRY_GRANT: `${BASE_URL}/studentStats/increaseQuizTryGrant`,
    DECREASE_QUIZ_TRY_GRANT: `${BASE_URL}/studentStats/decreaseQuizTryGrant`,

    GET_STUDENT_PRACTICE_EXERCISE_BY_ID: `${BASE_URL}/studentPracticeExerciseExercise/getById`,
    GET_STUDENT_PRACTICE_EXERCISE_BY_STUDENT_ID: `${BASE_URL}/studentPracticeExercise/getByStudentId`,
    GET_STUDENT_PRACTICE_EXERCISE_BY_STUDENT_ID_AND_EXERCISE_ID: `${BASE_URL}/studentPracticeExercise/getByStudentIdAndExerciseId`,
    CREATE_STUDENT_PRACTICE_EXERCISE: `${BASE_URL}/studentPracticeExercise/post`,
    UPDATE_STUDENT_PRACTICE_EXERCISE: `${BASE_URL}/studentPracticeExercise/update`,
    GET_STUDENT_PRACTICE_EXERCISE_BY_STUDENT_ID_AND_EXERCISE_ID_OR_CREATE: `${BASE_URL}/studentPracticeExercise/getByStudentIdAndExerciseIdOrCreate`,

    GET_ALL_FORMULAS: `${BASE_URL}/formula/getAll`,
    GET_FORMULA_BY_ID: `${BASE_URL}/formula/getById`,
    GET_FORMULA_BY_NAME: `${BASE_URL}/formula/getByName`,
    GET_FORMULA_BY_TYPE: `${BASE_URL}/formula/getByType`,

    GET_HELPER_BY_ID: `${BASE_URL}/helper/getById`,
    GET_HELPER_BY_CREATED_BY_AND_TYPE: `${BASE_URL}/helper/getByCreatedByAndType`,
    CREATE_HELPER: `${BASE_URL}/helper/post`,
    DELETE_HELPER_BY_ID: `${BASE_URL}/helper/deleteById`,

    GET_NOTIFICATION_BY_RECIPIENT_ID: `${BASE_URL}/notification/getByRecipientId`,
    UPDATE_NOTIFICATION: `${BASE_URL}/notification/update`,
}
